'use client';

import { useState } from 'react';
import { AppTopbar } from '@/components/app-topbar';
import { SeverityBadge } from '@/components/severity-badge';
import { REPORTS, formatDateTime, formatBytes, type Report } from '@/lib/mock-data';
import { FileText, Download, RefreshCw, Eye, ChevronDown, Filter, File } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

function dqaColor(score: number) {
  if (score >= 90) return 'text-[#27AE60]';
  if (score >= 75) return 'text-[#F1C40F]';
  return 'text-[#E67E22]';
}

const mockReportContent = `SAVVYCORTEX ANALYSIS REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by SCX Intelligence Engine v2.4.1
Powered by Savvy Analytics — savvyanalytics.info

EXECUTIVE SUMMARY
━━━━━━━━━━━━━━━━━
Dataset: sales_q1_2026.csv
Analysis Date: May 7, 2026 09:14 UTC
Overall DQA Score: 96.2%  [EXCELLENT]
Drift Severity: NONE

DATA QUALITY ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━
✓ Completeness     98.2%   Excellent
✓ Consistency      94.1%   Good
✓ Accuracy         97.8%   Excellent
✓ Uniqueness       99.1%   Excellent
✓ Validity         96.4%   Excellent
✓ Timeliness       95.8%   Excellent

DRIFT DETECTION
━━━━━━━━━━━━━━━
Baseline date: 2026-04-04
Columns monitored: 8
Drift events: 0
Status: BASELINE CLEAN — eligible for rotation after 2 more runs

KEY INSIGHTS
━━━━━━━━━━━━
01. Revenue grew 8.4% vs baseline period, driven by the Western region (+14.2%).
02. Units sold per transaction declined 2.1% — margin held steady.
03. E-commerce represents 38% of revenue, up from 34% in baseline.
04. No significant drift detected across monitored columns.

RECOMMENDATIONS
━━━━━━━━━━━━━━━
→ Consider rotating baseline after 2 more consecutive clean runs.
→ Monitor Western region volume for continued outperformance.
→ Review Eastern region for underperformance relative to baseline.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Confidential — Generated for demo@savvyanalytics.info
© 2026 Savvy Analytics, LLC — All rights reserved`;

export default function ReportsPage() {
  const { toast } = useToast();
  const [formatFilter, setFormatFilter] = useState<'all' | 'PDF' | 'DOCX'>('all');
  const [previewReport, setPreviewReport] = useState<Report | null>(null);
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('desc');

  const filtered = [...REPORTS]
    .filter(r => formatFilter === 'all' || r.format === formatFilter)
    .sort((a, b) => sortDir === 'desc'
      ? new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
      : new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()
    );

  return (
    <div className="min-h-screen bg-[#0A0A0A]">
      <AppTopbar title="Reports" subtitle="SCX Reports" />
      <div className="p-6 max-w-screen-2xl mx-auto">
        <div className="flex flex-wrap items-center gap-3 mb-5">
          <div className="flex items-center gap-1.5 text-xs font-mono text-[#6B6B6B]"><Filter size={12} />Filters:</div>
          <div className="flex gap-1 bg-[#1A1A1A] border border-[#3A3A3A] rounded-lg p-1">
            {(['all', 'PDF', 'DOCX'] as const).map(f => (
              <button
                key={f}
                onClick={() => setFormatFilter(f)}
                className={`px-3 py-1 rounded text-xs font-mono transition-all ${formatFilter === f ? 'bg-[#2A2A2A] text-white' : 'text-[#6B6B6B] hover:text-white'}`}
              >
                {f === 'all' ? 'All formats' : f}
              </button>
            ))}
          </div>
          <button
            onClick={() => setSortDir(d => d === 'asc' ? 'desc' : 'asc')}
            className="flex items-center gap-1 text-xs font-mono text-[#6B6B6B] hover:text-white transition-colors"
          >
            <ChevronDown size={12} className={sortDir === 'asc' ? 'rotate-180' : ''} />
            {sortDir === 'desc' ? 'Newest first' : 'Oldest first'}
          </button>
          <div className="ml-auto text-xs text-[#6B6B6B] font-mono">{filtered.length} reports</div>
        </div>

        <div className="grid lg:grid-cols-5 gap-5">
          <div className="lg:col-span-3">
            <div className="bg-[#111111] border border-[#2A2A2A] rounded-xl overflow-hidden">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-[#2A2A2A]">
                    {['Generated', 'Dataset', 'Format', 'DQA', 'Drift', 'Size', 'Actions'].map(h => (
                      <th key={h} className="text-left px-4 py-3 text-[10px] font-mono uppercase tracking-wider text-[#4A4A4A]">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {filtered.map(report => (
                    <tr
                      key={report.id}
                      className={`border-b border-[#1E1E1E] hover:bg-[#1A1A1A] cursor-pointer transition-colors ${
                        previewReport?.id === report.id ? 'bg-[#1A1A1A]' : ''
                      }`}
                      onClick={() => setPreviewReport(report)}
                    >
                      <td className="px-4 py-3">
                        <div className="font-data text-xs text-[#CCCCCC]">{formatDateTime(report.timestamp)}</div>
                      </td>
                      <td className="px-4 py-3">
                        <div className="text-sm text-white font-medium truncate max-w-[160px]">{report.dataset}</div>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`font-mono text-xs px-2 py-0.5 rounded ${
                          report.format === 'PDF' ? 'bg-[#C0392B]/10 text-[#C0392B]' : 'bg-[#3498DB]/10 text-[#3498DB]'
                        }`}>
                          {report.format}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`font-data text-xs font-bold ${dqaColor(report.dqaScore)}`}>{report.dqaScore}%</span>
                      </td>
                      <td className="px-4 py-3">
                        <SeverityBadge severity={report.driftSeverity} />
                      </td>
                      <td className="px-4 py-3">
                        <span className="font-data text-xs text-[#9A9A9A]">{formatBytes(report.sizeKb)}</span>
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-1">
                          <button
                            onClick={e => { e.stopPropagation(); setPreviewReport(report); }}
                            className="p-1.5 text-[#6B6B6B] hover:text-white hover:bg-[#2A2A2A] rounded transition-colors"
                            title="Preview"
                          >
                            <Eye size={13} />
                          </button>
                          <button
                            onClick={e => { e.stopPropagation(); toast({ title: 'Downloading report...', description: `${report.dataset} — ${report.format}` }); }}
                            className="p-1.5 text-[#6B6B6B] hover:text-[#D4A843] hover:bg-[#D4A843]/10 rounded transition-colors"
                            title="Download"
                          >
                            <Download size={13} />
                          </button>
                          <button
                            onClick={e => { e.stopPropagation(); toast({ title: 'Re-generating report...', description: `Re-running pipeline for ${report.dataset}` }); }}
                            className="p-1.5 text-[#6B6B6B] hover:text-[#27AE60] hover:bg-[#27AE60]/10 rounded transition-colors"
                            title="Re-generate"
                          >
                            <RefreshCw size={13} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Preview panel */}
          <div className="lg:col-span-2">
            {previewReport ? (
              <div className="bg-[#111111] border border-[#2A2A2A] rounded-xl overflow-hidden sticky top-20">
                <div className="px-5 py-4 border-b border-[#2A2A2A] flex items-center justify-between">
                  <div>
                    <div className="text-[10px] font-mono uppercase tracking-wider text-[#6B6B6B]">Report Preview</div>
                    <div className="text-sm font-medium text-white mt-0.5">{previewReport.dataset}</div>
                  </div>
                  <button
                    onClick={() => toast({ title: 'Downloading...', description: previewReport.dataset })}
                    className="flex items-center gap-1.5 text-xs bg-[#D4A843] text-black font-semibold px-3 py-1.5 rounded-lg hover:bg-[#E8C469]"
                  >
                    <Download size={12} /> Download
                  </button>
                </div>
                <div className="p-4">
                  <pre className="font-data text-[10px] text-[#9A9A9A] leading-relaxed whitespace-pre-wrap overflow-x-auto max-h-[500px] overflow-y-auto">
                    {mockReportContent}
                  </pre>
                </div>
              </div>
            ) : (
              <div className="bg-[#111111] border border-[#2A2A2A] rounded-xl p-10 text-center">
                <FileText size={28} className="mx-auto text-[#3A3A3A] mb-3" />
                <div className="text-[#6B6B6B] text-sm">Select a report to preview its contents</div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
